---
title: "Final Report"
subtitle: "HDI and Broadband - Data Analysis"
author: 'Group 01: Amie Leung, Ivan Nguyen, Janna Cameron, Kaye Ann Caroningan, and Syed Hassan'
output:
  html_document:
    toc: true
    toc_depth: '3'
---
<hr>
## Setup and Packages
```{r setup, echo=TRUE, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(tidy=TRUE, tidy.opts=list(width.cutoff=20))
library(tidyverse)
library(janitor)
library(skimr)
library(broom)
library(car)
library(lmtest)
```

## Loading the files
``` {r message=FALSE, warning=FALSE}
# getwd()
hdi <- read.csv("data/hdi_human_development_index.csv")
broadband <- read.csv("data/broadband_subscribers_per_100_people.csv")

glimpse(hdi)
glimpse(broadband)
```

## Processing Dataframes
### Cleaning header names
``` {r message=FALSE, warning=FALSE}
hdi_clean <- clean_names(hdi)
names(hdi_clean) <- gsub("^x", "", names(hdi_clean))
head(hdi_clean, 1)
broadband_clean <- clean_names(broadband)
names(broadband_clean) <- gsub("^x", "", names(broadband_clean))
head(broadband_clean, 1)
```

### Checking and removing duplicates
``` {r message=FALSE, warning=FALSE}
remove_duplicates <- function(data) {
  original_rows <- nrow(data)
  
  data_noDuplicates <- data %>%
    distinct()
  
  new_rows <- nrow(data_noDuplicates)
  
  rows_removed <- original_rows - new_rows
  print_statement <- paste(rows_removed, "rows removed.")
  cat(print_statement)
  
  return(data_noDuplicates)
}

hdi_clean <- remove_duplicates(hdi_clean)
broadband_clean <- remove_duplicates(broadband_clean)
```

### Handling missing values
``` {r message=FALSE, warning=FALSE}
skim(hdi_clean)
skim(broadband_clean)
```
``` {r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
cat("HDI: Number of empty records removed:", sum(is.na(hdi_clean)))
hdi_clean <- hdi_clean %>% drop_na() 

cat("Broadband: Number of empty records removed:", sum(is.na(broadband_clean)))
broadband_clean <- broadband_clean %>% drop_na() 

```
```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
# remove this later
data <- data.frame(
  A = c(1, 2, NA, 4),
  B = c(NA, 2, 3, 4),
  C = c(1, 2, 3, 4)
)

print(data)
cleaned_data <- data %>% drop_na()
print(cleaned_data)
```

```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
#Join the data by year and country
# merged_data_02 <- merge(broadband_clean, hdi_clean, by = c("country","year"))

#remove the missing values
# merged_data_02 <- na.omit(merged_data_02)
```

``` {r message=FALSE, warning=FALSE}

#changing the columns in broadband to dbl and treat missing values as NA
broadband <- broadband %>%
  mutate(across(c("X2003","X2004","X2005","X2006","X2010","X2011"),
                as.numeric))
```

``` {r message=FALSE, warning=FALSE}

#removing the chr "X" from the year name
names(broadband) <- gsub("^X","",names(broadband))
names(hdi) <- gsub("^X","",names(hdi))
```

``` {r message=FALSE, warning=FALSE}
#create a long table for easy analysis
broadband_long <- broadband %>%
  pivot_longer(cols=-country, names_to="year", values_to="broadband") %>%
  mutate(year=as.numeric(year))
hdi_long <- hdi %>%
  pivot_longer(cols=-country, names_to="year", values_to="hdi") %>%
  mutate(year=as.numeric(year))
```

``` {r message=FALSE, warning=FALSE}
#Join the data by year and country
merged_data <- merge(broadband_long, hdi_long, by = c("country","year"))

#remove the missing values
merged_data <- na.omit(merged_data)
```

## Data Visualization

``` {r message=FALSE, warning=FALSE}
#visualize the relationship between broadband subscription and HDI over the time
ggplot(merged_data, aes(x = broadband, y = hdi)) +
  geom_point(alpha = 0.6, color = "steelblue") +
  geom_smooth(method = "lm", color = "darkred") +
  theme_minimal() +
  labs(title = "Relationship between Broadband Subscriptions and HDI",
       x = "Broadband subscriptions per 100 people",
       y = "Human Development Index")
```

#Looking at the first research question 
#What is the relationship between HDI and broadband subscriptions, based on the latest available data, which is 2023.

``` {r message=FALSE, warning=FALSE}
#Pull the data for 2023 only
data_2023 <- merged_data %>% filter(year==2023)
```

``` {r message=FALSE, warning=FALSE}

#Test the skewness and distribution of the data
#Histogram of HDI in 2023. Histogram show that the HDI of 2023 is left skewed
ggplot(data_2023,aes(x=hdi))+
  geom_histogram(colour="white", fill="steelblue")+
  labs(title="Histogram of HDI in 2023",
       x = "HDI",
       y = "Frequency")
```

``` {r message=FALSE, warning=FALSE}

# Box plot of HDI in 2023
ggplot(data_2023, aes(y=hdi)) + 
  geom_boxplot() + 
  labs(title = "Box plot of HDI in 2023",
       y="Count")
```

``` {r message=FALSE, warning=FALSE}
#Histogram of broadband in 2023. Histogram show that the broadband data is right skewed
ggplot(data_2023,aes(x=broadband))+
  geom_histogram(colour="white", fill="steelblue")+
  labs(title="Histogram of Broadband in 2023",
       x = "Broadband",
       y = "Frequency")
```

``` {r message=FALSE, warning=FALSE}
# Box plot of broadband in 2023
ggplot(data_2023, aes(y=broadband)) + 
  geom_boxplot() + 
  labs(title = "Box plot of Broadband in 2023",
       y="Count")
```

``` {r message=FALSE, warning=FALSE}
#Need to transform the dataset
data_2023 <- data_2023 %>%
  mutate(broadband = ifelse(broadband == 0, NA, broadband)) %>%
  mutate(log_broadband = log(broadband))
```


``` {r message=FALSE, warning=FALSE}
#Create a scatter plot of log broadband vs log hdi of 2023
ggplot(data_2023, aes(x = log_broadband, y = hdi)) +
  geom_point(color = "steelblue") +                                               # Add scatter points
  geom_smooth(method = "lm", color = "darkred", linetype = "solid") + # Adds a linear regression line
  labs(title = "Scatter Plot with Line of Best Fit of Log Broadband vs HDI",
       x = "Log Broadband Subscription per 100",
       y = "HDI")
```

``` {r message=FALSE, warning=FALSE}
#Create a model
m1 <- lm(hdi ~ log_broadband, data=data_2023)
summary(m1)
```


